version: 2

defaults: &defaults
  docker:
    - image: circleci/node:15.14.0
  working_directory: ~/gatsby-starter-lumen

jobs:
  install:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          keys:
            - dependencies-{{ checksum "yarn.lock" }}
      - run: yarn install --frozen-lockfile
      - save_cache:
          paths:
            - node_modules
          key: dependencies-{{ checksum "yarn.lock" }}

  lint:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          keys:
            - dependencies-{{ checksum "yarn.lock" }}
      - run: yarn lint

  test:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          keys:
            - dependencies-{{ checksum "yarn.lock" }}
      - run: yarn test --runInBand --no-cache

  coverage:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          keys:
            - dependencies-{{ checksum "yarn.lock" }}
      - run: yarn test:coverage --runInBand --no-cache
      - save_cache:
          key: coverage-{{ .Environment.CIRCLE_SHA1 }}
          paths:
            - coverage

  codecov:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          keys:
            - dependencies-{{ checksum "yarn.lock" }}
      - restore_cache:
          keys:
            - coverage-{{ .Environment.CIRCLE_SHA1 }}
      - run: yarn global add codecov
      - run: yarn codecov
    
workflows:
  version: 2
  test:
    jobs:
      - install
      - lint:
          requires:
            - install
      - test:
          requires:
            - install
      - coverage:
          requires:
            - install
      - codecov:
          requires:
            - coverage
"@jimp/custom@^0.14.0":
  version "0.14.0"
  resolved "https://registry.yarnpkg.com/@jimp/custom/-/custom-0.14.0.tgz#1dbbf0094df7403f4e03bc984ed92e7458842f74"
  integrity sha512-kQJMeH87+kWJdVw8F9GQhtsageqqxrvzg7yyOw3Tx/s7v5RToe8RnKyMM+kVtBJtNAG+Xyv/z01uYQ2jiZ3GwA==
  dependencies:
    "@babel/runtime" "^7.7.2"
    "@jimp/core" "^0.14.0"

"@jimp/gif@^0.14.0":
  version "0.14.0"
  resolved "https://registry.yarnpkg.com/@jimp/gif/-/gif-0.14.0.tgz#db159f57c3cfd1566bbe8b124958791998614960"
  integrity sha512-DHjoOSfCaCz72+oGGEh8qH0zE6pUBaBxPxxmpYJjkNyDZP7RkbBkZJScIYeQ7BmJxmGN4/dZn+MxamoQlr+UYg==
  dependencies:
    "@babel/runtime" "^7.7.2"
    "@jimp/utils" "^0.14.0"
    gifwrap "^0.9.2"
    omggif "^1.0.9"

"@jimp/jpeg@^0.14.0":
  version "0.14.0"
  resolved "https://registry.yarnpkg.com/@jimp/jpeg/-/jpeg-0.14.0.tgz#8a687a6a653bbbae38c522edef8f84bb418d9461"
  integrity sha512-561neGbr+87S/YVQYnZSTyjWTHBm9F6F1obYHiyU3wVmF+1CLbxY3FQzt4YolwyQHIBv36Bo0PY2KkkU8BEeeQ==
  dependencies:
    "@babel/runtime" "^7.7.2"
    "@jimp/utils" "^0.14.0"
    jpeg-js "^0.4.0"

"@jimp/plugin-blit@^0.14.0":
  version "0.14.0"
  resolved "https://registry.yarnpkg.com/@jimp/plugin-blit/-/plugin-blit-0.14.0.tgz#5eb374be1201313b2113899fb842232d8fcfd345"
  integrity sha512-YoYOrnVHeX3InfgbJawAU601iTZMwEBZkyqcP1V/S33Qnz9uzH1Uj1NtC6fNgWzvX6I4XbCWwtr4RrGFb5CFrw==
  dependencies:
    "@babel/runtime" "^7.7.2"
    "@jimp/utils" "^0.14.0"

"@jimp/plugin-blur@^0.14.0":
  version "0.14.0"
  resolved "https://registry.yarnpkg.com/@jimp/plugin-blur/-/plugin-blur-0.14.0.tgz#fe07e4932d5a2f5d8c9831e245561553224bfc60"
  integrity sha512-9WhZcofLrT0hgI7t0chf7iBQZib//0gJh9WcQMUt5+Q1Bk04dWs8vTgLNj61GBqZXgHSPzE4OpCrrLDBG8zlhQ==
  dependencies:
    "@babel/runtime" "^7.7.2"
    "@jimp/utils" "^0.14.0"

"@jimp/plugin-circle@^0.14.0":
  version "0.14.0"
  resolved "https://registry.yarnpkg.com/@jimp/plugin-circle/-/plugin-circle-0.14.0.tgz#82c0e904a34e90fa672fb9c286bc892e92088ddf"
  integrity sha512-o5L+wf6QA44tvTum5HeLyLSc5eVfIUd5ZDVi5iRfO4o6GT/zux9AxuTSkKwnjhsG8bn1dDmywAOQGAx7BjrQVA==
  dependencies:
    "@babel/runtime" "^7.7.2"
    "@jimp/utils" "^0.14.0"

"@jimp/plugin-color@^0.14.0":
  version "0.14.0"
  resolved "https://registry.yarnpkg.com/@jimp/plugin-color/-/plugin-color-0.14.0.tgz#772bd2d80a88bc66ea1331d010207870f169a74b"
  integrity sha512-JJz512SAILYV0M5LzBb9sbOm/XEj2fGElMiHAxb7aLI6jx+n0agxtHpfpV/AePTLm1vzzDxx6AJxXbKv355hBQ==
  dependencies:
    "@babel/runtime" "^7.7.2"
    "@jimp/utils" "^0.14.0"
    tinycolor2 "^1.4.1"

"@jimp/plugin-contain@^0.14.0":
  version "0.14.0"
  resolved "https://registry.yarnpkg.com/@jimp/plugin-contain/-/plugin-contain-0.14.0.tgz#c68115420d182e696f81bbe76fb5e704909b2b6a"
  integrity sha512-RX2q233lGyaxiMY6kAgnm9ScmEkNSof0hdlaJAVDS1OgXphGAYAeSIAwzESZN4x3ORaWvkFefeVH9O9/698Evg==
  dependencies:
    "@babel/runtime" "^7.7.2"
    "@jimp/utils" "^0.14.0"

"@jimp/plugin-cover@^0.14.0":
  version "0.14.0"
  resolved "https://registry.yarnpkg.com/@jimp/plugin-cover/-/plugin-cover-0.14.0.tgz#4755322589c5885e44e14e31b86b542e907297ce"
  integrity sha512-0P/5XhzWES4uMdvbi3beUgfvhn4YuQ/ny8ijs5kkYIw6K8mHcl820HahuGpwWMx56DJLHRl1hFhJwo9CeTRJtQ==
  dependencies:
    "@babel/runtime" "^7.7.2"
    "@jimp/utils" "^0.14.0"

"@jimp/plugin-crop@^0.14.0":
  version "0.14.0"
  resolved "https://registry.yarnpkg.com/@jimp/plugin-crop/-/plugin-crop-0.14.0.tgz#4cbd856ca84ffc37230fad2534906f2f75aa3057"
  integrity sha512-Ojtih+XIe6/XSGtpWtbAXBozhCdsDMmy+THUJAGu2x7ZgKrMS0JotN+vN2YC3nwDpYkM+yOJImQeptSfZb2Sug==
  dependencies:
    "@babel/runtime" "^7.7.2"
    "@jimp/utils" "^0.14.0"

"@jimp/plugin-displace@^0.14.0":
  version "0.14.0"
  resolved "https://registry.yarnpkg.com/@jimp/plugin-displace/-/plugin-displace-0.14.0.tgz#b0e6a57d00cb1f893f541413fe9d737d23c3b70c"
  integrity sha512-c75uQUzMgrHa8vegkgUvgRL/PRvD7paFbFJvzW0Ugs8Wl+CDMGIPYQ3j7IVaQkIS+cAxv+NJ3TIRBQyBrfVEOg==
  dependencies:
    "@babel/runtime" "^7.7.2"
    "@jimp/utils" "^0.14.0"

"@jimp/plugin-dither@^0.14.0":
  version "0.14.0"
  resolved "https://registry.yarnpkg.com/@jimp/plugin-dither/-/plugin-dither-0.14.0.tgz#9185ec4c38e02edc9e5831f5d709f6ba891e1b93"
  integrity sha512-g8SJqFLyYexXQQsoh4dc1VP87TwyOgeTElBcxSXX2LaaMZezypmxQfLTzOFzZoK8m39NuaoH21Ou1Ftsq7LzVQ==
  dependencies:
    "@babel/runtime" "^7.7.2"
    "@jimp/utils" "^0.14.0"

"@jimp/plugin-fisheye@^0.14.0":
  version "0.14.0"
  resolved "https://registry.yarnpkg.com/@jimp/plugin-fisheye/-/plugin-fisheye-0.14.0.tgz#9f26346cf2fbc660cc2008cd7fd30a83b5029e78"
  integrity sha512-BFfUZ64EikCaABhCA6mR3bsltWhPpS321jpeIQfJyrILdpFsZ/OccNwCgpW1XlbldDHIoNtXTDGn3E+vCE7vDg==
  dependencies:
    "@babel/runtime" "^7.7.2"
    "@jimp/utils" "^0.14.0"

"@jimp/plugin-flip@^0.14.0":
  version "0.14.0"
  resolved "https://registry.yarnpkg.com/@jimp/plugin-flip/-/plugin-flip-0.14.0.tgz#7966d6aa3b5fe1aa4d2d561ff12b8ef5ccb9b071"
  integrity sha512-WtL1hj6ryqHhApih+9qZQYA6Ye8a4HAmdTzLbYdTMrrrSUgIzFdiZsD0WeDHpgS/+QMsWwF+NFmTZmxNWqKfXw==
  dependencies:
    "@babel/runtime" "^7.7.2"
    "@jimp/utils" "^0.14.0"

"@jimp/plugin-gaussian@^0.14.0":
  version "0.14.0"
  resolved "https://registry.yarnpkg.com/@jimp/plugin-gaussian/-/plugin-gaussian-0.14.0.tgz#452bc1971a4467ad9b984aa67f4c200bf941bb65"
  integrity sha512-uaLwQ0XAQoydDlF9tlfc7iD9drYPriFe+jgYnWm8fbw5cN+eOIcnneEX9XCOOzwgLPkNCxGox6Kxjn8zY6GxtQ==
  dependencies:
    "@babel/runtime" "^7.7.2"
    "@jimp/utils" "^0.14.0"

"@jimp/plugin-invert@^0.14.0":
  version "0.14.0"
  resolved "https://registry.yarnpkg.com/@jimp/plugin-invert/-/plugin-invert-0.14.0.tgz#cd31a555860e9f821394936d15af161c09c42921"
  integrity sha512-UaQW9X9vx8orQXYSjT5VcITkJPwDaHwrBbxxPoDG+F/Zgv4oV9fP+udDD6qmkgI9taU+44Fy+zm/J/gGcMWrdg==
  dependencies:
    "@babel/runtime" "^7.7.2"
    "@jimp/utils" "^0.14.0"

"@jimp/plugin-mask@^0.14.0":
  version "0.14.0"
  resolved "https://registry.yarnpkg.com/@jimp/plugin-mask/-/plugin-mask-0.14.0.tgz#52619643ac6222f85e6b27dee33c771ca3a6a4c9"
  integrity sha512-tdiGM69OBaKtSPfYSQeflzFhEpoRZ+BvKfDEoivyTjauynbjpRiwB1CaiS8En1INTDwzLXTT0Be9SpI3LkJoEA==
  dependencies:
    "@babel/runtime" "^7.7.2"
    "@jimp/utils" "^0.14.0"

"@jimp/plugin-normalize@^0.14.0":
  version "0.14.0"
  resolved "https://registry.yarnpkg.com/@jimp/plugin-normalize/-/plugin-normalize-0.14.0.tgz#bf39e356b6d473f582ce95633ad49c9cdb82492b"
  integrity sha512-AfY8sqlsbbdVwFGcyIPy5JH/7fnBzlmuweb+Qtx2vn29okq6+HelLjw2b+VT2btgGUmWWHGEHd86oRGSoWGyEQ==
  dependencies:
    "@babel/runtime" "^7.7.2"
    "@jimp/utils" "^0.14.0"

"@jimp/plugin-print@^0.14.0":
  version "0.14.0"
  resolved "https://registry.yarnpkg.com/@jimp/plugin-print/-/plugin-print-0.14.0.tgz#1c43c2a92a7adc05b464863882cb89ce486d63e6"
  integrity sha512-MwP3sH+VS5AhhSTXk7pui+tEJFsxnTKFY3TraFJb8WFbA2Vo2qsRCZseEGwpTLhENB7p/JSsLvWoSSbpmxhFAQ==
  dependencies:
    "@babel/runtime" "^7.7.2"
    "@jimp/utils" "^0.14.0"
    load-bmfont "^1.4.0"

"@jimp/plugin-resize@^0.14.0":
  version "0.14.0"
  resolved "https://registry.yarnpkg.com/@jimp/plugin-resize/-/plugin-resize-0.14.0.tgz#ef7fc6c2e45f8bcab62456baf8fd3bc415b02b64"
  integrity sha512-qFeMOyXE/Bk6QXN0GQo89+CB2dQcXqoxUcDb2Ah8wdYlKqpi53skABkgVy5pW3EpiprDnzNDboMltdvDslNgLQ==
  dependencies:
    "@babel/runtime" "^7.7.2"
    "@jimp/utils" "^0.14.0"

"@jimp/plugin-rotate@^0.14.0":
  version "0.14.0"
  resolved "https://registry.yarnpkg.com/@jimp/plugin-rotate/-/plugin-rotate-0.14.0.tgz#3632bc159bf1c3b9ec9f459d9c05d02a11781ee7"
  integrity sha512-aGaicts44bvpTcq5Dtf93/8TZFu5pMo/61lWWnYmwJJU1RqtQlxbCLEQpMyRhKDNSfPbuP8nyGmaqXlM/82J0Q==
  dependencies:
    "@babel/runtime" "^7.7.2"
    "@jimp/utils" "^0.14.0"

"@jimp/plugin-scale@^0.14.0":
  version "0.14.0"
  resolved "https://registry.yarnpkg.com/@jimp/plugin-scale/-/plugin-scale-0.14.0.tgz#d30f0cd1365b8e68f43fa423300ae7f124e9bf10"
  integrity sha512-ZcJk0hxY5ZKZDDwflqQNHEGRblgaR+piePZm7dPwPUOSeYEH31P0AwZ1ziceR74zd8N80M0TMft+e3Td6KGBHw==
  dependencies:
    "@babel/runtime" "^7.7.2"
    "@jimp/utils" "^0.14.0"

"@jimp/plugin-shadow@^0.14.0":
  version "0.14.0"
  resolved "https://registry.yarnpkg.com/@jimp/plugin-shadow/-/plugin-shadow-0.14.0.tgz#471fdb9f109ff2d9e20d533d45e1e18e0b48c749"
  integrity sha512-p2igcEr/iGrLiTu0YePNHyby0WYAXM14c5cECZIVnq/UTOOIQ7xIcWZJ1lRbAEPxVVXPN1UibhZAbr3HAb5BjQ==
  dependencies:
    "@babel/runtime" "^7.7.2"
    "@jimp/utils" "^0.14.0"

"@jimp/plugin-threshold@^0.14.0":
  version "0.14.0"
  resolved "https://registry.yarnpkg.com/@jimp/plugin-threshold/-/plugin-threshold-0.14.0.tgz#ebd72721c7d1d518c5bb6e494e55d97ac3351d3b"
  integrity sha512-N4BlDgm/FoOMV/DQM2rSpzsgqAzkP0DXkWZoqaQrlRxQBo4zizQLzhEL00T/YCCMKnddzgEhnByaocgaaa0fKw==
  dependencies:
    "@babel/runtime" "^7.7.2"
    "@jimp/utils" "^0.14.0"

"@jimp/plugins@^0.14.0":
  version "0.14.0"
  resolved "https://registry.yarnpkg.com/@jimp/plugins/-/plugins-0.14.0.tgz#41dba85f15ab8dadb4162100eb54e5f27b93ee2c"
  integrity sha512-vDO3XT/YQlFlFLq5TqNjQkISqjBHT8VMhpWhAfJVwuXIpilxz5Glu4IDLK6jp4IjPR6Yg2WO8TmRY/HI8vLrOw==
  dependencies:
    "@babel/runtime" "^7.7.2"
    "@jimp/plugin-blit" "^0.14.0"
    "@jimp/plugin-blur" "^0.14.0"
    "@jimp/plugin-circle" "^0.14.0"
    "@jimp/plugin-color" "^0.14.0"
    "@jimp/plugin-contain" "^0.14.0"
    "@jimp/plugin-cover" "^0.14.0"
    "@jimp/plugin-crop" "^0.14.0"
    "@jimp/plugin-displace" "^0.14.0"
    "@jimp/plugin-dither" "^0.14.0"
    "@jimp/plugin-fisheye" "^0.14.0"
    "@jimp/plugin-flip" "^0.14.0"
    "@jimp/plugin-gaussian" "^0.14.0"
    "@jimp/plugin-invert" "^0.14.0"
    "@jimp/plugin-mask" "^0.14.0"
    "@jimp/plugin-normalize" "^0.14.0"
    "@jimp/plugin-print" "^0.14.0"
    "@jimp/plugin-resize" "^0.14.0"
    "@jimp/plugin-rotate" "^0.14.0"
    "@jimp/plugin-scale" "^0.14.0"
    "@jimp/plugin-shadow" "^0.14.0"
    "@jimp/plugin-threshold" "^0.14.0"
    timm "^1.6.1"

"@jimp/png@^0.14.0":
  version "0.14.0"
  resolved "https://registry.yarnpkg.com/@jimp/png/-/png-0.14.0.tgz#0f2dddb5125c0795ca7e67c771204c5437fcda4b"
  integrity sha512-0RV/mEIDOrPCcNfXSPmPBqqSZYwGADNRVUTyMt47RuZh7sugbYdv/uvKmQSiqRdR0L1sfbCBMWUEa5G/8MSbdA==
  dependencies:
    "@babel/runtime" "^7.7.2"
    "@jimp/utils" "^0.14.0"
    pngjs "^3.3.3"

"@jimp/tiff@^0.14.0":
  version "0.14.0"
  resolved "https://registry.yarnpkg.com/@jimp/tiff/-/tiff-0.14.0.tgz#a5b25bbe7c43fc3b07bad4e2ab90e0e164c1967f"
  integrity sha512-zBYDTlutc7j88G/7FBCn3kmQwWr0rmm1e0FKB4C3uJ5oYfT8645lftUsvosKVUEfkdmOaMAnhrf4ekaHcb5gQw==
  dependencies:
    "@babel/runtime" "^7.7.2"
    utif "^2.0.1"

"@jimp/types@^0.14.0":
  version "0.14.0"
  resolved "https://registry.yarnpkg.com/@jimp/types/-/types-0.14.0.tgz#ef681ff702883c5f105b5e4e30d49abf39ee9e34"
  integrity sha512-hx3cXAW1KZm+b+XCrY3LXtdWy2U+hNtq0rPyJ7NuXCjU7lZR3vIkpz1DLJ3yDdS70hTi5QDXY3Cd9kd6DtloHQ==
  dependencies:
    "@babel/runtime" "^7.7.2"
    "@jimp/bmp" "^0.14.0"
    "@jimp/gif" "^0.14.0"
    "@jimp/jpeg" "^0.14.0"
    "@jimp/png" "^0.14.0"
    "@jimp/tiff" "^0.14.0"
    timm "^1.6.1"

"@jimp/utils@^0.14.0":
  version "0.14.0"
  resolved "https://registry.yarnpkg.com/@jimp/utils/-/utils-0.14.0.tgz#296254e63118554c62c31c19ac6b8c4bfe6490e5"
  integrity sha512-MY5KFYUru0y74IsgM/9asDwb3ERxWxXEu3CRCZEvE7DtT86y1bR1XgtlSliMrptjz4qbivNGMQSvUBpEFJDp1A==
  dependencies:
    "@babel/runtime" "^7.7.2"
    regenerator-runtime "^0.13.3"

"@mdx-js/util@^2.0.0-next.8":
  version "2.0.0-next.8"
  resolved "https://registry.yarnpkg.com/@mdx-js/util/-/util-2.0.0-next.8.tgz#66ecc27b78e07a3ea2eb1a8fc5a99dfa0ba96690"
  integrity sha512-T0BcXmNzEunFkuxrO8BFw44htvTPuAoKbLvTG41otyZBDV1Rs+JMddcUuaP5vXpTWtgD3grhcrPEwyx88RUumQ==

"@mikaelkristiansson/domready@^1.0.10":
  version "1.0.11"
  resolved "https://registry.yarnpkg.com/@mikaelkristiansson/domready/-/domready-1.0.11.tgz#6a4b5891dccb6402ff4e944de843036ee1ffd4f5"
  integrity sha512-nEBLOa0JgtqahmPrnJZ18epLiFBzxhdKgo4uhN3TaBFRmM30pEVrS9FAEV4tg92d8PTdU+dYQx2lnpPyFMgMcg==

"@nodelib/fs.scandir@2.1.4":
  version "2.1.4"
  resolved "https://registry.yarnpkg.com/@nodelib/fs.scandir/-/fs.scandir-2.1.4.tgz#d4b3549a5db5de2683e0c1071ab4f140904bbf69"
  integrity sha512-33g3pMJk3bg5nXbL/+CY6I2eJDzZAni49PfJnL5fghPTggPvBd/pFNSgJsdAgWptuFu7qq/ERvOYFlhvsLTCKA==
  dependencies:
    "@nodelib/fs.stat" "2.0.4"
    run-parallel "^1.1.9"

"@nodelib/fs.stat@2.0.4", "@nodelib/fs.stat@^2.0.2":
  version "2.0.4"
  resolved "https://registry.yarnpkg.com/@nodelib/fs.stat/-/fs.stat-2.0.4.tgz#a3f2dd61bab43b8db8fa108a121cfffe4c676655"
  integrity sha512-IYlHJA0clt2+Vg7bccq+TzRdJvv19c2INqBSsoOLp1je7xjtr7J26+WXR72MCdvU9q1qTzIWDfhMf+DRvQJK4Q==

"@nodelib/fs.walk@^1.2.3", "@nodelib/fs.walk@^1.2.4":
  version "1.2.6"
  resolved "https://registry.yarnpkg.com/@nodelib/fs.walk/-/fs.walk-1.2.6.tgz#cce9396b30aa5afe9e3756608f5831adcb53d063"
  integrity sha512-8Broas6vTtW4GIXTAHDoE32hnN2M5ykgCpWGbuXHQ15vEMqr23pB76e/GZcYsZCHALv50ktd24qhEyKr6wBtow==
  dependencies:
    "@nodelib/fs.scandir" "2.1.4"
    fastq "^1.6.0"

"@octokit/auth-token@^2.4.0":
  version "2.4.5"
  resolved "https://registry.yarnpkg.com/@octokit/auth-token/-/auth-token-2.4.5.tgz#568ccfb8cb46f36441fac094ce34f7a875b197f3"
  integrity sha512-BpGYsPgJt05M7/L/5FoE1PiAbdxXFZkX/3kDYcsvd1v6UhlnE5e96dTDr0ezX/EFwciQxf3cNV0loipsURU+WA==
  dependencies:
    "@octokit/types" "^6.0.3"

"@octokit/endpoint@^6.0.1":
  version "6.0.11"
  resolved "https://registry.yarnpkg.com/@octokit/endpoint/-/endpoint-6.0.11.tgz#082adc2aebca6dcefa1fb383f5efb3ed081949d1"
  integrity sha512-fUIPpx+pZyoLW4GCs3yMnlj2LfoXTWDUVPTC4V3MUEKZm48W+XYpeWSZCv+vYF1ZABUm2CqnDVf1sFtIYrj7KQ==
  dependencies:
    "@octokit/types" "^6.0.3"
    is-plain-object "^5.0.0"
    universal-user-agent "^6.0.0"

"@octokit/openapi-types@^6.0.0":
  version "6.0.0"
  resolved "https://registry.yarnpkg.com/@octokit/openapi-types/-/openapi-types-6.0.0.tgz#7da8d7d5a72d3282c1a3ff9f951c8133a707480d"
  integrity sha512-CnDdK7ivHkBtJYzWzZm7gEkanA7gKH6a09Eguz7flHw//GacPJLmkHA3f3N++MJmlxD1Fl+mB7B32EEpSCwztQ==
